name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master, '*']
    types: [opened, synchronize]
  schedule:
    - cron: '0 0 * * *' # This will run the pipeline once a day at midnight UTC
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to run the Playwright tests in'
        required: true
        default: 'whqa'

run-name: Running tests on environement ${{github.event.inputs.environment}}

jobs:
  test:
    name: 'Running tests on [environement: ${{github.event.inputs.environment}}]'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: TEST_ENV=${{ github.event.inputs.environment || 'whqa' }} npx playwright test
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
